// SPDX-License-Identifier: GPL-2.0-or-later
//
// Stubs for the two generated megafunctions, for simulating without them.
//
// rtl/pll_pix.v and rtl/pll_reconfig.v are generated by Quartus and committed,
// because a bitstream build needs them. When they are present iverilog picks
// them up from rtl/*.v and these stubs would be a second declaration of the
// same modules:
//
//   sim/vendor_stubs.v:70: error: 'pll_pix' has already been declared
//   rtl/pll_pix.v:8:      : It was declared here as a module.
//
// So they live here rather than in vendor_stubs.v, and the Makefile includes
// this file only when the generated ones are absent -- a checkout that has not
// run Quartus yet, which is most of them.
//
// See docs/MEGAFUNCTIONS.md for generating the real ones.

`timescale 1ns/1ps
`default_nettype none

/* Stands in for the generated Altera PLL. Two fixed outputs; reconfiguration
 * ports accepted and ignored, since functional sim does not retune. */
module pll_pix (
    input  wire        refclk,
    input  wire        rst,
    output wire        outclk_0,
    output wire        outclk_1,
    output wire        locked,
    input  wire [63:0] reconfig_to_pll,
    output wire [63:0] reconfig_from_pll
);
    reg c0 = 1'b0, c1 = 1'b0;
    always #39.68254 c0 = ~c0;          // 12.6 MHz
    always #79.36508 c1 = ~c1;          //  6.3 MHz
    assign outclk_0 = c0;
    assign outclk_1 = c1;
    assign locked   = 1'b1;
    assign reconfig_from_pll = 64'd0;
endmodule

/* Stands in for altera_pll_reconfig. Accepts the Avalon slave and never
 * stalls; functional sim does not model the reconfiguration shift. */
module pll_reconfig (
    input  wire        mgmt_clk,
    input  wire        mgmt_reset,
    input  wire [5:0]  mgmt_address,
    input  wire        mgmt_read,
    output wire [31:0] mgmt_readdata,
    input  wire        mgmt_write,
    input  wire [31:0] mgmt_writedata,
    output wire        mgmt_waitrequest,
    output wire [63:0] reconfig_to_pll,
    input  wire [63:0] reconfig_from_pll
);
    assign mgmt_readdata    = 32'd0;
    assign mgmt_waitrequest = 1'b0;
    assign reconfig_to_pll  = 64'd0;
endmodule

/* Stands in for the hardened HPS general-purpose interface. In sim gp_out is
 * held idle; a testbench that wants to inject ARM writes drives the DUT's
 * gp_out net directly rather than through this. */
