#!/usr/bin/env python3
"""Generate the u-boot override that MiSTer hands to the bootloader.

The file names the bitstream inside it, so generating the two together stops
them drifting apart. It also lets the load address and partition be set without
editing anything by hand.

MiSTer's u-boot is a fork with exFAT support added, and the FAT partition may
answer to `load` or to `fatload` on partition 1 or 2. Without a serial console
a wrong guess fails silently, so every combination is tried in turn.

Usage:
    python3 tools/gen_uboot_txt.py quartus/output_files/blitscrt.txt
    python3 tools/gen_uboot_txt.py out.txt --rbf myname.rbf --loadaddr 0x2000000
    python3 tools/gen_uboot_txt.py out.txt --linux    # M2 onward, boots a kernel
"""
import argparse
import sys


def build(rbf, loadaddr, parts, cmds, bootdelay, linux, kernel, dtb, bootargs,
          bridges):
    tries = []
    for p in parts:
        for c in cmds:
            tries.append("%s mmc 0:%d ${loadaddr} %s" % (c, p, rbf))
    loadrbf = " || ".join(tries)

    out = []
    out.append("# u-boot override for blitsCRT_Mister")
    out.append("#")
    out.append("# GENERATED by tools/gen_uboot_txt.py -- do not edit.")
    out.append("# Regenerate with: make uboot-txt")
    out.append("#")
    out.append("# MiSTer reads this when %s is selected from the menu, writes it" % rbf)
    out.append("# to DDR3 with a magic header, drops the HPS-to-FPGA bridges and warm")
    out.append("# reboots. u-boot then runs these commands instead of its own.")
    out.append("#")
    out.append("# The load is attempted %d ways because MiSTer's u-boot is a fork with" % len(tries))
    out.append("# exFAT support and the partition layout varies. A serial console and")
    out.append("# 'printenv' will tell you which one is real.")
    out.append("")
    out.append("bootdelay=%d" % bootdelay)
    out.append("")
    out.append("# Set explicitly. If this u-boot defines no loadaddr, ${loadaddr}")
    out.append("# expands to nothing and every load below fails for the wrong reason.")
    out.append("# Clear of the env block MiSTer leaves at 0x1FFFF000.")
    out.append("loadaddr=%s" % loadaddr)
    out.append("")
    out.append("loadrbf=%s" % loadrbf)
    out.append("")

    if not linux:
        out.append("# M1 is fabric only. No HPS component, so the bridges stay down and")
        out.append("# nothing boots after the bitstream is configured.")
        out.append("bootcmd=run loadrbf; fpga load 0 ${loadaddr} ${filesize}; "
                   "echo blitsCRT_Mister configured -- halting before Linux")
    else:
        ktries, dtries = [], []
        for p in parts:
            for c in cmds:
                ktries.append("%s mmc 0:%d ${kernaddr} %s" % (c, p, kernel))
                dtries.append("%s mmc 0:%d ${dtbaddr} %s" % (c, p, dtb))
        out.append("kernaddr=0x1000000")
        out.append("dtbaddr=0x3000000")
        out.append("loadkern=%s" % " || ".join(ktries))
        out.append("loaddtb=%s" % " || ".join(dtries))
        out.append("bootargs=%s" % bootargs)
        out.append("")
        if bridges:
            out.append("# bridge enable: correct once the design has an HPS component")
            out.append("# with slaves behind the bridges (M3+). Enabled with --bridges.")
            bridge = "bridge enable; "
        else:
            out.append("# Bridges left down. The kernel-boot proof touches no fabric")
            out.append("# registers, so there is nothing behind the bridges to reach")
            out.append("# yet -- one fewer variable. Turn on later with --bridges.")
            bridge = ""
        out.append("bootcmd=run loadrbf; fpga load 0 ${loadaddr} ${filesize}; "
                   "%srun loadkern; run loaddtb; "
                   "bootz ${kernaddr} - ${dtbaddr}" % bridge)

    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out", nargs="?", default="quartus/output_files/blitscrt.txt")
    ap.add_argument("--rbf", default="blitscrt.rbf")
    ap.add_argument("--loadaddr", default="0x2000000")
    ap.add_argument("--partitions", default="1,2",
                    help="FAT partition numbers to try, in order")
    ap.add_argument("--commands", default="load,fatload",
                    help="u-boot load commands to try, in order")
    ap.add_argument("--bootdelay", type=int, default=2)
    ap.add_argument("--linux", action="store_true",
                    help="also boot a kernel (M2 onward)")
    ap.add_argument("--kernel", default="blitscrt/zImage")
    ap.add_argument("--dtb", default="blitscrt/blitscrt.dtb")
    # No 'quiet': the proof is watching the boot on the serial console.
    ap.add_argument("--bootargs", default="console=ttyS0,115200")
    ap.add_argument("--bridges", action="store_true",
                    help="add 'bridge enable' to bootcmd (M3+, once a slave exists)")
    a = ap.parse_args()

    parts = [int(x) for x in a.partitions.split(",")]
    cmds = [x.strip() for x in a.commands.split(",")]

    text = build(a.rbf, a.loadaddr, parts, cmds, a.bootdelay,
                 a.linux, a.kernel, a.dtb, a.bootargs, a.bridges)

    if a.out == "-":
        sys.stdout.write(text)
    else:
        import os
        d = os.path.dirname(a.out)
        if d:
            os.makedirs(d, exist_ok=True)
        with open(a.out, "w") as f:
            f.write(text)
        print("wrote %s: %s, %d load attempts, %s"
              % (a.out, a.rbf, len(parts) * len(cmds),
                 "boots Linux" if a.linux else "halts after fpga load"))


if __name__ == "__main__":
    main()
